### ISSUE TITLE
Some items crafting with Applied Energistics 2

### ISSUE THREAD

**Issue by Bogreaper** [BedrockLegends/BRL-Support#10]
*Please check the open and  closed issues before posting an issue!*

#### Issue description:
When you attempt to craft either an item frame or a small crate the game exits with the error code, Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes.

#### Steps to reproduce:
1. look item up in jei
2. Click + to add parts to crafting terminal
3. Wait for game to crash, load saved game.

#### Version (make sure you are on the latest version before reporting):
**Forge Version:**  14.23.5.2847
**Server Version:**  Single Player
**Modpack Version:**  9.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by BedrockLegends** [comment]
Its cause of hillariously large NBT data that ae2 cant handle and we have no way to fix it as its on AE2s end and your like the 2nd person to report this but we cant fix it
