### ISSUE TITLE
Recipe conflict between string mesh and silk

### ISSUE THREAD

**Issue by BRBonobo** [BedrockLegends/BRL-Support#11]
*Please check the open and  closed issues before posting an issue!*

#### Steps to reproduce:
1. Fill a crafting table or station with string in a 3x3
2. Only allows me to craft Silk from Erebus, can't make a string mesh.
3. Can't progress as intended
![station](https://user-images.githubusercontent.com/62994708/78131257-a01e8280-73cf-11ea-96d8-c0f481aaaf6a.png)
![table](https://user-images.githubusercontent.com/62994708/78131260-a0b71900-73cf-11ea-80a0-b1f4884bc2ac.png)

#### Version (make sure you are on the latest version before reporting):
**Forge Version: 14.23.5.2847** 
**Single Player** 
**Modpack Version: 11.0** (from Twitch Launcher 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by BedrockLegends** [comment]
See The little arrow with number 3 on it click on that to get your recipe as thats how u fix this

**Comment by BRBonobo** [comment]
Thanks! I love you now.
