### ISSUE TITLE
issue with slab Machines

### ISSUE THREAD

**Issue by Andychrdk** [BedrockLegends/BRL-Support#14]
*Please check the open and  closed issues before posting an issue!*

#### Issue description:
on the slap Furnes if you right click it you will mount it like a chair.

#### Steps to reproduce:
1. build a Slab Furnes
2. plaze the furnes
3. open the furnes and you mount it.

#### Version (make sure you are on the latest version before reporting):
**Forge Version:*14.23.5.2847* 
**Server Version:*11.4* 
**Modpack Version:*11.4* 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Andychrdk** [comment]
Small update.
the mounting only happen if you click on the furnes bear hands. if you have item in the hand it opens normaly

**Comment by BedrockLegends** [comment]
Not a bug, Its from one of the mods doing that
