### ISSUE TITLE
GalactiCraft Recipe Error

### ISSUE THREAD

**Issue by 2Squarey** [BedrockLegends/BRL-Support#5]
Unable to make Compressed Zinc in order to advance to tier 8 and above rockets.  Zinc in the recipe is not able to be made using the current ore JEI states to use.

**Comment by lectavison** [comment]
The crushing and smelting recipes for Neptune Zinc Ore are currently being over ridden by the Zollern Galaxy mod which is preventing the creation of the proper type of zinc.
