### ISSUE TITLE
cant download the pack because of the missing item

### ISSUE THREAD

**Issue by Sa-kai** [BedrockLegends/BRL-Support#7]
*Please check the open and  closed issues before posting an issue!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting): yes,latest version
**Forge Version:** 
**Server Version:** 
**Modpack Version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
https://media.discordapp.net/attachments/663799783219134465/668837140783955999/unknown.png?width=838&height=474

**Comment by BedrockLegends** [comment]
Not a bug I had no issues installing it with twitch

**Comment by Sa-kai** [comment]
i restart the lanuncher and it worked my bad XD
