### ISSUE TITLE
Rotten flesh on drying rack > 2 different items

### ISSUE THREAD

**Issue by Sa-kai** [BedrockLegends/BRL-Support#8]
*Please check the open and  closed issues before posting an issue!*

#### Issue description:soo on the recipy to get leather is to put rotten flesh on drying rack and wait 8min and 30 sec,but you also get monster jerky after first 5 min of drying
![unknown](https://user-images.githubusercontent.com/49068691/72786629-5aef0f00-3c2e-11ea-8213-7cfcf1a589e0.png)

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge Version:** 
**Server Version:** 
**Modpack Version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by MasterSloth1** [comment]
yea its our lazy way of making it so u cant get leather via that method lol 😄

**Comment by Sa-kai** [comment]
ah,allright,thanks
