### ISSUE TITLE
Recipe Error

### ISSUE THREAD

**Issue by Knoxxar** [BedrockLegends/BRL-Support#9]
*Please check the open and  closed issues before posting an issue!*

#### Issue description:
When i login on the Server, i get some recipe errors via chat.

#### Steps to reproduce:
1.Give you OP
2.Login onto a Server

#### Version (make sure you are on the latest version before reporting):
**Forge Version: 14.23.5.2847
**Server Version: 6.8  forge 14.23.5.2847
**Modpack Version: 7.8 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
I have some screenshots:

https://cdn.discordapp.com/attachments/585854045378314249/670560509283663882/unknown.png

https://cdn.discordapp.com/attachments/585854045378314249/670560644201840640/unknown.png

https://cdn.discordapp.com/attachments/585854045378314249/670616936383512596/unknown.png

**Comment by BedrockLegends** [comment]
Umm based on your screenshots, it is recipe from the 1.15 version and we don't not take bug reports for 1.15 nor do we accept bug reports for 1.15. These recipes are attached to the 1.15 pack as I just checked
